### ISSUE TITLE
Make it obvious if you're on a demo vs live site for a portal

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/cap#101]
An env var would cause there to be a banner or something that says this is our test environment, just like the one that is there for the "new"  user interface changes.  And a link to a page on GitHub that explains that this is a test environment, subject to be broken, and to not put permanent links to it. Test/demo urls subject to change. Then that URL can be shared with groups like LoP and LAC with the site being properly documented that it isn't the site that patrons would be looking at. 

It could also just be "CAP_TEST=true" , where the existence means it is in test mode, and the non-existence means production.

- [x] set up environment variable denoting environment
- [x] edit robots.txt
- [x] create the banner for test and demo (differentiated)
- [x] create /version page which displays the $DOCKER_IMAGE

**Comment by RussellMcOrmond** [comment]
This feature should also change the robots.txt to indicate to search engines not to index the test sites.

https://github.com/crkn-rcdr/cap/blob/9b18cdf8f0105676b580000cf61002c32108d011/CAP/lib/CAP/Controller/Root.pm#L196-L209


There is a desire to have both "test" and "demo", and it may be appropriate to differentiate in the banner.

I have also set up a variable that indicates the docker image that is running.  I suggest that this be available somewhere, possibly as a path like /version

**Comment by RussellMcOrmond** [comment]
https://www-demo.canadiana.ca/robots.txt

If the right environment variable is set, that should be outputting.


```
User-agent: *
Disallow: /
```

https://www.robotstxt.org/robotstxt.html

**Comment by jjfriedman** [comment]
Per @RussellMcOrmond 's comment in https://github.com/crkn-rcdr/Systems-Administration/issues/489. What's the level of effort/feasibility of implementing this in the near future?

**Comment by brittnylapierre** [comment]
Hey @RussellMcOrmond and @jjfriedman I will work on this straight away, and let @RussellMcOrmond know when the images should be pushed to demo and test. Then we will let you know that they are ready @jjfriedman

**Comment by brittnylapierre** [comment]
@RussellMcOrmond do I just do this in cap's perl code to access your docker image variable? $ENV{'DOCKER_IMAGE'};

**Comment by brittnylapierre** [comment]
Nevermind looks like yes!

**Comment by brittnylapierre** [comment]
Okay I have everything ready for review - my 2 uncertain areas are: your DOCKER_IMAGE env var will just automatically work right? I put a line in the Dockerfile for my testing, ENV DOCKER_IMAGE = 1234a which worked when accessing $ENV{'DOCKER_IMAGE'};

Then also is putting the environment variable in cap.conf okay? I'm not sure of the best way for that ~
See line 42:
# Which environment is running? Can be one of: demo, test, or production
environment = test

**Comment by RussellMcOrmond** [comment]
We have moved all the configuration to environment variables, which are substituted into the config with a module https://metacpan.org/pod/Catalyst::Plugin::ConfigLoader::Environment

There are very few enviroment variables shows in the current  https://github.com/crkn-rcdr/cap/blob/quick-fixes-viewer/docker-compose.override.yml.example , but it gives an idea.


Here is what the environment looks like for the demo docker-compose.yml at the moment (passwords are all in puppet environment variables, so not shown here).


```
services:
  capdemo:
    image: ${capimagedemo}
    environment:
      - DOCKER_IMAGE=${capimagedemo}
      - CAP_Model::Presentation_image_endpoint=https://image-${capcontentdemo}/iiif/2
      - CAP_Model::Presentation_swift_container_preservation=https://swift.canadiana.ca/v1/AUTH_crkn/preservation-cihm-aip
      - CAP_Model::Presentation_swift_container_access=https://swift.canadiana.ca/v1/AUTH_crkn/access-files
      - 'CAP_Model::Presentation_swift_temp_url_key=${cappassword}'
      - CAP_Model::Presentation_server=${capcouch}/copresentation2
      - CAP_Model::Search_server=${capsolr}/solr/cosearch2
      - CAP_Model::Parl_server=${capcouch}/copresentation2
```



I believe I will need to set an environment variable:

`CAP_environment=demo`

What you want to do is have the default of `environment = production` in the cap.conf that will be inside the container.


If it is easier, I can also use the environment variable name `CAP_dockerimage` rather than `DOCKER_IMAGE` if you would rather this be something that is substituted in the config.
